// <auto-generated />
using System;
using E_Wallet_Alpha.DataAccessLayer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace E_Wallet_Alpha.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("E_Wallet_Alpha.Models.Transiction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountOfMoney")
                        .HasColumnType("integer");

                    b.Property<string>("ToWhom")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("TransictionTable");
                });

            modelBuilder.Entity("E_Wallet_Alpha.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("E_Wallet_Alpha.Models.Transiction", b =>
                {
                    b.HasOne("E_Wallet_Alpha.Models.User", null)
                        .WithMany("Transictions")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("E_Wallet_Alpha.Models.User", b =>
                {
                    b.Navigation("Transictions");
                });
#pragma warning restore 612, 618
        }
    }
}
